plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.ahicode'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

ext {
	jjwtVersion = '0.11.5'
	junitVersion = '5.7.0'
	dotenvVersion = '5.2.2'
	openApiVersion = '2.0.2'
	pdfboxVersion = '2.0.14'
	mockitoVersion = '3.6.28'
	restAssuredVersion = '5.3.2'
	testcontainersVersion = '1.17.3'
	redisTestContainerVersion = '2.2.2'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring dependencies
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-amqp'
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// Databases dependencies
	runtimeOnly 'org.postgresql:postgresql'
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-database-postgresql'

	// Utility dependencies
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	implementation "io.jsonwebtoken:jjwt-api:${jjwtVersion}"
	implementation "io.jsonwebtoken:jjwt-impl:${jjwtVersion}"
	implementation "org.apache.pdfbox:pdfbox:${pdfboxVersion}"
	implementation "io.jsonwebtoken:jjwt-jackson:${jjwtVersion}"
	implementation "io.github.cdimascio:java-dotenv:${dotenvVersion}"

	// Test dependencies
	testImplementation 'com.h2database:h2'
	testImplementation 'org.testcontainers:postgresql'
	testImplementation 'org.testcontainers:junit-jupiter'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation "org.mockito:mockito-core:${mockitoVersion}"
	testImplementation 'org.springframework.security:spring-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation "io.rest-assured:rest-assured:${restAssuredVersion}"
	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testImplementation "org.testcontainers:testcontainers:${testcontainersVersion}"
	testImplementation "com.redis:testcontainers-redis:${redisTestContainerVersion}"
	testImplementation "org.testcontainers:testcontainers-bom:${testcontainersVersion}"
}

tasks.named('test') {
	useJUnitPlatform()
}
