server.port=8080

spring.application.name=TextMe

application.security.jwt.access-token.secret-key=${JWT_ACCESS_TOKEN_SECRET_KEY}
application.security.jwt.access-token.expiration=3600000
application.security.jwt.refresh-token.secret-key=${JWT_REFRESH_TOKEN_SECRET_KEY}
application.security.jwt.refresh-token.expiration=604800000
