server.port=8080

spring.application.name=TaskFlow

spring.redis.port=6379
spring.redis.host=127.0.0.1

spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.host=smtp.yandex.ru
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}

spring.rabbitmq.port=5672
spring.rabbitmq.host=localhost
spring.rabbitmq.username=${KUYAN_USER}
spring.rabbitmq.password=${KUYAN_PASS}

spring.datasource.username=${APP_DB_USER}
spring.datasource.password=${APP_DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/app_db

spring.jpa.hibernate.ddl-auto=none

spring.jackson.time-zone=UTC

application.security.jwt.access-token.secret-key=${JWT_ACCESS_TOKEN_SECRET_KEY}
application.security.jwt.access-token.expiration=3600000
application.security.jwt.refresh-token.secret-key=${JWT_REFRESH_TOKEN_SECRET_KEY}
application.security.jwt.refresh-token.expiration=604800000
