package com.ahicode.TextMe.model.enums;

public enum Action {
    CREATE_PROJECT,
    READ_PROJECT,
    UPDATE_PROJECT,
    DELETE_PROJECT,
    INVITE_MEMBER,
    EXCLUDE_MEMBER,
    CHANGE_MEMBER_ROLE,
    VIEW_LIST_OF_MEMBERS,
    CREATE_TASK,
    READ_TASK,
    ASSIGN_TASK,
    UPDATE_INFO_OF_TASK,
    CHANGE_STATUS_OF_TASK,
    VIEW_LIST_OF_TASKS,
    DELETE_TASK,
    GET_REPORT;
}
